### ISSUE TITLE
`No such interface` supported on Windows 11 - build 22000.493

### ISSUE THREAD

**Issue by LexiconCode** [mrob95/pyvda#11]
Edition	Windows 11 Pro
Version	21H2
Installed on	‎1/‎29/‎2022
OS build	22000.493
Experience	Windows Feature Experience Pack 1000.22000.493.0

```
Exception from function create_work_space:
Traceback (most recent call last):
  File "C:\Users\Main\AppData\Local\Programs\Python\Python38-32\lib\site-packages\dragonfly\actions\action_function.py", line 145, in _execute
    self._function(**arguments)
  File "D:\Backup\Library\Documents\Code\Caster\castervoice\lib\windows_virtual_desktops.py", line 26, in create_work_space
    n = len(pyvda.get_virtual_desktops())
  File "C:\Users\Main\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pyvda\pyvda.py", line 421, in get_virtual_desktops
    manager_internal = get_vd_manager_internal()
  File "C:\Users\Main\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pyvda\utils.py", line 37, in get_vd_manager_internal
    return _get_object(IVirtualDesktopManagerInternal, CLSID_VirtualDesktopManagerInternal)
  File "C:\Users\Main\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pyvda\utils.py", line 26, in _get_object
    pServiceProvider.QueryService(
_ctypes.COMError: (-2147467262, 'No such interface supported', (None, None, None, 0, None))
Execution failed: 'create_work_space'(): (-2147467262, 'No such interface supported', (None, None, None, 0, None))
```

{B2F925B9-5A0F-4D2E-9F4D-2B1507593C10} exists.
![image](https://user-images.githubusercontent.com/24551569/153977040-9820051e-37e5-4b47-9fcd-e530227b5d7e.png)

However the build version BUILD_OVER_21313  is being skipped and it makes it down to the if statement.
https://github.com/mrob95/pyvda/blob/2b8eaaf0416b065248f31b594c4c830ec3738365/pyvda/com_defns.py#L244

The root analysis is `sys.getwindowsversion().build` is reporting `9200` on my machine.

However running the above code through the interpreter:

```
>>> import sys
>>> sys.getwindowsversion().build
22000
```

So I'm left scratching my head a little bit on this one that it could be Natlink related.

**Comment by mrob95** [comment]
Very weird! I think you're right that it's probably natlink related. 

It looks like Python uses Win32 `GetVersionExW` under the hood to get the version info, and according to the docs:

> If compatibility mode is in effect, the GetVersionEx function reports the operating system as it identifies itself, which may not be the operating system that is installed. For example, if compatibility mode is in effect, GetVersionEx reports the operating system that is selected for application compatibility.

https://docs.microsoft.com/en-us/windows/win32/api/sysinfoapi/nf-sysinfoapi-getversionexw

I wonder if either Natlink or Dragon is running in compatibility mode for an ancient version of Windows?

As a test, could you try hardcoding `BUILD_OVER_21313` to `True` and see if everything works running in Natlink? Might need to get a bit smarter about detecting Windows versions.

**Comment by LexiconCode** [comment]
> Could you also try `sys.getwindowsversion().platform_version` while running in Natlink? If that reports the correct version then it's an easy fix.
Looking good! `10, 0, 22000`

**Comment by mrob95** [comment]
Nice! Will push a fixed version tonight 👍

**Comment by mrob95** [comment]
https://github.com/mrob95/pyvda/pull/12 should have fixed this.

Could you give version `0.2.4` a go and make sure?

**Comment by LexiconCode** [comment]
> #12 should have fixed this.
> 
> Could you give version `0.2.4` a go and make sure?

Sure

**Comment by mrob95** [comment]
Nice, thanks! 👍
