### ISSUE TITLE
Add support for Change Virtual Desktop Background on Windows 11

### ISSUE THREAD

**Issue by mrob95** [mrob95/pyvda#13]
Interfaces for this are available on Windows 11. I've added the interface definitions for these functions to https://github.com/mrob95/pyvda/blob/master/pyvda/com_defns.py#L216-L220 but have not linked these up to the VirtualDesktop class.

I don't have access to a Windows 11 machine atm, so if someone is on Windows 11 and can make a PR for a set_wallpaper method that would be great. It should raise an error if BUILD_OVER_21313 is not True.

**Comment by reckoner** [comment]
I have windows 11. I downloaded the master branch and it passes all tests. What else can I do?

**Comment by mrob95** [comment]
If you'd like to implement this, then you'll need to add a new method to the `VirtualDesktop` class called `set_wallpaper`.

This should take a string (path to the wallpaper) and will need to call this method on the virtual desktop manager:
https://github.com/mrob95/pyvda/blob/master/pyvda/com_defns.py#L224

**Comment by mrob95** [comment]
This is now implemented, thanks @reckoner :)
