### ISSUE TITLE
Windows 11 22H2 - Exception when calling get_virtual_desktops

### ISSUE THREAD

**Issue by Leo40Git** [mrob95/pyvda#15]
Attempting to call `get_virtual_desktops()` on my Windows 11 22H2 (build 22621.1) machine throws this error:
`_ctypes.COMError: (-2147023116, 'A null reference pointer was passed to the stub.', (None, None, None, 0, None))`

**Comment by mrob95** [comment]
Thanks for reporting this. I don't currently have access to a windows 11 PC to test, but am going to try downloading a developer VM to see if I can repro it this weekend.

**Comment by Leo40Git** [comment]
It's an Insider build, so I'm not surprised there's no standalone download. I mean, you could _maybe_ try to update your VM to Insider by logging into it with a Microsoft account that owns Windows (I'm... actually not sure if that's a requirement for the Insider program. It probably is?)

ANYWAY, I'm gonna go look into the interface definition now. Just gotta wait for VS to finish updating...

**Comment by Leo40Git** [comment]
Well that didn't go well. I couldn't even find `IVirtualDesktopManagerInternal`, and when I tried to view the proxy definition of `IVirtualDesktopManager` (the closest thing I _could_ find), well...
![Damn null pointer exceptions.](https://user-images.githubusercontent.com/7997354/171810119-f4e0a5a9-0255-4687-96f9-ce50a166c015.png)

**Comment by Leo40Git** [comment]
New discoveries:
- GUID is now `b2f925b9-5a0f-4d2e-9f4d-2b1507593c10`! (from [this](https://github.com/mntone/VirtualDesktop/pull/1#issuecomment-951921603))
- Name is now _also_ `B2F925B9-5A0F-4D2E-9F4D-2B1507593C10`, apparently - explains why I couldn't find them by name, I guess.
- "View Proxy Definition" is just borked on my machine...

**Comment by mrob95** [comment]
Thanks, that is very useful info and should be enough to fix the issue. 

Out of interest based on this comment:
> they are in the registry but the interface names have been replaced by the ids so the function that searches by name fails.

Are you able to find the proxy definition if you search for `B2F925B9` as the name?

**Comment by Leo40Git** [comment]
> Are you able to find the proxy definition if you search for `B2F925B9` as the name?

Yes.
![image](https://user-images.githubusercontent.com/7997354/171844800-8f3d14e1-c3c3-4219-b786-b68b5f5bce55.png)

**Comment by mrob95** [comment]
Does "view proxy definition" work there or is it borked for them all?

**Comment by Leo40Git** [comment]
Nope, it's broken for everyone.

**Comment by mrob95** [comment]
Is there a setting in win11 to control whether you have one "stack" of virtual desktops per monitor or one stack across all monitors?

**Comment by Leo40Git** [comment]
Doesn't seem like it. In fact, looks like opening Task View in one monitor opens it in all monitors.

**Comment by mrob95** [comment]
Okay, could you give this PR a try and see if that fixes it?

https://github.com/mrob95/pyvda/pull/16

I'm still a bit confused by the naming of "GetAllCurrentDesktops" - what does it mean for a desktop to not be current?

**Comment by Leo40Git** [comment]
Running the test suite with #16 seems to fix everything but `test_create_and_remove_desktop`, which fails on the assertion that `new_count == (old_count + 1)`.

It _does_ successfully add a new desktop, but then fails to detect it...?

**Comment by mrob95** [comment]
I've pushed an update which just adds some better error messages to the tests. Would be interested to know what it thinks new_count and old_count are - 0 or 1 for both maybe?

**Comment by Leo40Git** [comment]
Before the update, both `old_count` and `new_count` were 1 - `get_all_desktops` wasn't returning the desktop that was just created, apparently.

**Comment by Leo40Git** [comment]
```
>       assert new_count == expected_count, f"Wanted {expected_count}, got {new_count}"
E       AssertionError: Wanted 2, got 1
E       assert 1 == 2```

**Comment by mrob95** [comment]
Hmm. My theory is that Microsoft are planning to release a feature at some point which allows you to use a different stack of virtual desktops for each monitor. That would explain why they have added all of these new integer parameters - you have to pass in the id of the monitor you want the desktops for. It would also explain the `GetDesktopPerMonitor` and `SetDesktopPerMonitor` functions, which imply that such a setting exists, or will exist in the future.

Given this I don't think `GetAllCurrentDesktops` is the call we want. It's only going to give us an array of the desktops which are currently active - so if you had three monitors it would give back three desktops. That's why it's currently only giving back one - because we only have one stack of desktops.

What we want is to figure out what we need to pass into `GetDesktops` to get it to give us back all of the desktops on the one stack. Setting it to 0 worked in previous builds but now it is complaining about a null pointer.

I've pushed another update passing in 1, just in case they are using 1-indexed monitor IDs. I don't have high hopes that that will work though.

**Comment by Leo40Git** [comment]
...why did that _work_.

Congratulations, you've apparently thinking on the same track as Microsoft.

**Comment by mrob95** [comment]
...interesting. What happens if we pass in 2? 🤔

**Comment by mzomparelli** [comment]
You pass in IntPtr.Zero

**Comment by mzomparelli** [comment]
I had to figure that out for my app - https://github.com/mzomparelli/zVirtualDesktop

**Comment by mzomparelli** [comment]
I just reviewed your code and it appears the proc you're missing in IVirtualDesktopManagerInternal is:

`IObjectArray GetAllCurrentDesktops();`

**Comment by mzomparelli** [comment]
The unknown one in that interface is:

`void GetDesktopSwitchIncludeExcludeViews(IVirtualDesktop desktop, out IObjectArray o1, out IObjectArray o2);`

**Comment by mrob95** [comment]
Thanks @mzomparelli - I think it was the `GetAllCurrentDesktops` prototype that we were missing, which I've now added in #16. The "what do we need to pass into `GetDesktops`?" question may have been a red herring :)

**Comment by Leo40Git** [comment]
Updated to 0.2.6, now I get this error:
```
Traceback (most recent call last):
  File "C:\Users\<USER>\Documents\script.py", line 7, in <module>
    from pyvda import get_virtual_desktops, VirtualDesktop, AppView
  File "C:\Users\<USER>\AppData\Local\Programs\Python\Python310\lib\site-packages\pyvda\__init__.py", line 51, in <module>
    from .pyvda import (
  File "C:\Users\<USER>\AppData\Local\Programs\Python\Python310\lib\site-packages\pyvda\pyvda.py", line 24, in <module>
    managers = Managers()
  File "C:\Users\<USER>\AppData\Local\Programs\Python\Python310\lib\site-packages\pyvda\utils.py", line 52, in __init__
    self.manager_internal2 = get_vd_manager_internal2()
  File "C:\Users\<USER>\AppData\Local\Programs\Python\Python310\lib\site-packages\pyvda\utils.py", line 41, in get_vd_manager_internal2
    return _get_object(IVirtualDesktopManagerInternal2, CLSID_VirtualDesktopManagerInternal)
  File "C:\Users\<USER>\AppData\Local\Programs\Python\Python310\lib\site-packages\pyvda\utils.py", line 27, in _get_object
    pServiceProvider.QueryService(
_ctypes.COMError: (-2147467262, 'No such interface supported', (None, None, None, 0, None))
```

**Comment by mrob95** [comment]
Whoops. Could you try 0.2.7 @Leo40Git ?

**Comment by Leo40Git** [comment]
0.2.7 works perfectly!

**Comment by mrob95** [comment]
Nice, thanks for the report and for your help fixing it :)
