### ISSUE TITLE
VirtualDesktop go method throws COMError

### ISSUE THREAD

**Issue by RonUlitsky** [mrob95/pyvda#27]
```
Traceback (most recent call last):
  File "C:\Users\Me\AppData\Local\Programs\Python\Python310\lib\site-packages\pyvda\pyvda.py", line 375, in go
    managers.manager_internal.SwitchDesktop(*NULL_IF_OVER_20231, self._virtual_desktop)
_ctypes.COMError: (-2147024809, 'The parameter is incorrect.', (None, None, None, 0, None))
```

Haven't been able to thoroughly test this but figured I should make an issue on the off chance that someone knows what's going on. This is version 0.3.0 on Windows 11 so I'm aware you might not have a machine that runs that.

**Comment by mrob95** [comment]
Could you try updating to version `0.3.1` and see if that fixes it?

**Comment by RonUlitsky** [comment]
That fixed it! Big thanks for all your work.
