### ISSUE TITLE
permission problem

### ISSUE THREAD

**Issue by pykernel** [mrob95/pyvda#30]
I have a few questions to consider:
1、How do I set permissions on virtual desktops
2、I want to hide the virtual desktop taskbar window

**Comment by mrob95** [comment]
Could you give more detail?

**Comment by pykernel** [comment]
> Could you give more detail?

After a desktop is created, users are forbidden to switch to other desktops through the taskbar. Do I need any permission to set this parameter?

**Comment by mrob95** [comment]
I'm not sure I understand what you mean. Unless there is a new permissions feature in Windows 11 that I'm not aware of, there are no permissions involved. Users can create and delete virtual desktops as they want. This library just provides a Python API for the already existing Windows features, it doesn't implement anything else on top.

**Comment by pykernel** [comment]
> I'm not sure I understand what you mean. Unless there is a new permissions feature in Windows 11 that I'm not aware of, there are no permissions involved. Users can create and delete virtual desktops as they want. This library just provides a Python API for the already existing Windows features, it doesn't implement anything else on top.

Thank you for your reply. I have a question to consult. 
I want to disable switching to the original desktop after creating a new desktop. And do not show the original desktop in the preview window, is there a solution?

**Comment by mrob95** [comment]
I think the only way to do this would be to remove the original desktop after creating the new one.
