### ISSUE TITLE
Reordering desktops on Windows 10 build 19044

### ISSUE THREAD

**Issue by macsunmood** [mrob95/pyvda#6]
The desktops reordering feature was made available in the latest Win10 builds (starting from [Windows 10 build 21337](https://winaero.com/windows-10-build-21337-allows-you-to-re-order-and-rename-virtual-desktops-and-much-more/)).

Is it possible to implement it somehow programmatically on a Win10 build without native support, particularly 19044 ?

**Comment by macsunmood** [comment]
@mrob95 ..and swaps the desktop names.. This could be a solution I guess, since you don't need desktop moving much often and hence it shouldn't be really optimized in speed and convenience.

**Comment by mrob95** [comment]
Going to close this. Let me know if you have any issues :)
